export const countries = [
    { value: "AF", label: "Afghanistan", phone: "93" },
    { value: "AL", label: "Albania", phone: "355" },
    { value: "DZ", label: "Algeria", phone: "213" },
    { value: "AD", label: "Andorra", phone: "376" },
    { value: "AO", label: "Angola", phone: "244" },
    { value: "AG", label: "Antigua and Barbuda", phone: "1-268" },
    { value: "AR", label: "Argentina", phone: "54" },
    { value: "AM", label: "Armenia", phone: "374" },
    { value: "AU", label: "Australia", phone: "61" },
    { value: "AT", label: "Austria", phone: "43" },
    { value: "AZ", label: "Azerbaijan", phone: "994" },
    { value: "BS", label: "Bahamas", phone: "1-242" },
    { value: "BH", label: "Bahrain", phone: "973" },
    { value: "BD", label: "Bangladesh", phone: "880" },
    { value: "BB", label: "Barbados", phone: "1-246" },
    { value: "BY", label: "Belarus", phone: "375" },
    { value: "BE", label: "Belgium", phone: "32" },
    { value: "BZ", label: "Belize", phone: "501" },
    { value: "BJ", label: "Benin", phone: "229" },
    { value: "BT", label: "Bhutan", phone: "975" },
    { value: "BO", label: "Bolivia", phone: "591" },
    { value: "BA", label: "Bosnia and Herzegovina", phone: "387" },
    { value: "BW", label: "Botswana", phone: "267" },
    { value: "BR", label: "Brazil", phone: "55" },
    { value: "BN", label: "Brunei", phone: "673" },
    { value: "BG", label: "Bulgaria", phone: "359" },
    { value: "BF", label: "Burkina Faso", phone: "226" },
    { value: "BI", label: "Burundi", phone: "257" },
    { value: "CV", label: "Cabo Verde", phone: "238" },
    { value: "KH", label: "Cambodia", phone: "855" },
    { value: "CM", label: "Cameroon", phone: "237" },
    { value: "CA", label: "Canada", phone: "1" },
    { value: "CF", label: "Central African Republic", phone: "236" },
    { value: "TD", label: "Chad", phone: "235" },
    { value: "CL", label: "Chile", phone: "56" },
    { value: "CN", label: "China", phone: "86" },
    { value: "CO", label: "Colombia", phone: "57" },
    { value: "KM", label: "Comoros", phone: "269" },
    { value: "CG", label: "Congo (Brazzaville)", phone: "242" },
    { value: "CD", label: "Congo (Kinshasa)", phone: "243" },
    { value: "CR", label: "Costa Rica", phone: "506" },
    { value: "HR", label: "Croatia", phone: "385" },
    { value: "CU", label: "Cuba", phone: "53" },
    { value: "CY", label: "Cyprus", phone: "357" },
    { value: "CZ", label: "Czechia", phone: "420" },
    { value: "DK", label: "Denmark", phone: "45" },
    { value: "DJ", label: "Djibouti", phone: "253" },
    { value: "DM", label: "Dominica", phone: "1-767" },
    { value: "DO", label: "Dominican Republic", phone: "1" },
    { value: "EC", label: "Ecuador", phone: "593" },
    { value: "EG", label: "Egypt", phone: "20" },
    { value: "SV", label: "El Salvador", phone: "503" },
    { value: "GQ", label: "Equatorial Guinea", phone: "240" },
    { value: "ER", label: "Eritrea", phone: "291" },
    { value: "EE", label: "Estonia", phone: "372" },
    { value: "SZ", label: "Eswatini", phone: "268" },
    { value: "ET", label: "Ethiopia", phone: "251" },
    { value: "FJ", label: "Fiji", phone: "679" },
    { value: "FI", label: "Finland", phone: "358" },
    { value: "FR", label: "France", phone: "33" },
    { value: "GA", label: "Gabon", phone: "241" },
    { value: "GM", label: "Gambia", phone: "220" },
    { value: "GE", label: "Georgia", phone: "995" },
    { value: "DE", label: "Germany", phone: "49" },
    { value: "GH", label: "Ghana", phone: "233" },
    { value: "GR", label: "Greece", phone: "30" },
    { value: "GD", label: "Grenada", phone: "1-473" },
    { value: "GT", label: "Guatemala", phone: "502" },
    { value: "GN", label: "Guinea", phone: "224" },
    { value: "GW", label: "Guinea-Bissau", phone: "245" },
    { value: "GY", label: "Guyana", phone: "592" },
    { value: "HT", label: "Haiti", phone: "509" },
    { value: "HN", label: "Honduras", phone: "504" },
    { value: "HU", label: "Hungary", phone: "36" },
    { value: "IS", label: "Iceland", phone: "354" },
    { value: "IN", label: "India", phone: "91" },
    { value: "ID", label: "Indonesia", phone: "62" },
    { value: "IR", label: "Iran", phone: "98" },
    { value: "IQ", label: "Iraq", phone: "964" },
    { value: "IE", label: "Ireland", phone: "353" },
    { value: "IL", label: "Israel", phone: "972" },
    { value: "IT", label: "Italy", phone: "39" },
    { value: "CI", label: "Ivory Coast", phone: "225" },
    { value: "JM", label: "Jamaica", phone: "1-876" },
    { value: "JP", label: "Japan", phone: "81" },
    { value: "JO", label: "Jordan", phone: "962" },
    { value: "KZ", label: "Kazakhstan", phone: "7" },
    { value: "KE", label: "Kenya", phone: "254" },
    { value: "KI", label: "Kiribati", phone: "686" },
    { value: "KW", label: "Kuwait", phone: "965" },
    { value: "KG", label: "Kyrgyzstan", phone: "996" },
    { value: "LA", label: "Laos", phone: "856" },
    { value: "LV", label: "Latvia", phone: "371" },
    { value: "LB", label: "Lebanon", phone: "961" },
    { value: "LS", label: "Lesotho", phone: "266" },
    { value: "LR", label: "Liberia", phone: "231" },
    { value: "LY", label: "Libya", phone: "218" },
    { value: "LI", label: "Liechtenstein", phone: "423" },
    { value: "LT", label: "Lithuania", phone: "370" },
    { value: "LU", label: "Luxembourg", phone: "352" },
    { value: "MG", label: "Madagascar", phone: "261" },
    { value: "MW", label: "Malawi", phone: "265" },
    { value: "MY", label: "Malaysia", phone: "60" },
    { value: "MV", label: "Maldives", phone: "960" },
    { value: "ML", label: "Mali", phone: "223" },
    { value: "MT", label: "Malta", phone: "356" },
    { value: "MH", label: "Marshall Islands", phone: "692" },
    { value: "MR", label: "Mauritania", phone: "222" },
    { value: "MU", label: "Mauritius", phone: "230" },
    { value: "MX", label: "Mexico", phone: "52" },
    { value: "FM", label: "Micronesia", phone: "691" },
    { value: "MD", label: "Moldova", phone: "373" },
    { value: "MC", label: "Monaco", phone: "377" },
    { value: "MN", label: "Mongolia", phone: "976" },
    { value: "ME", label: "Montenegro", phone: "382" },
    { value: "MA", label: "Morocco", phone: "212" },
    { value: "MZ", label: "Mozambique", phone: "258" },
    { value: "MM", label: "Myanmar (formerly Burma)", phone: "95" },
    { value: "NA", label: "Namibia", phone: "264" },
    { value: "NR", label: "Nauru", phone: "674" },
    { value: "NP", label: "Nepal", phone: "977" },
    { value: "NL", label: "Netherlands", phone: "31" },
    { value: "NZ", label: "New Zealand", phone: "64" },
    { value: "NI", label: "Nicaragua", phone: "505" },
    { value: "NE", label: "Niger", phone: "227" },
    { value: "NG", label: "Nigeria", phone: "234" },
    { value: "KP", label: "North Korea", phone: "850" },
    { value: "MK", label: "North Macedonia", phone: "389" },
    { value: "NO", label: "Norway", phone: "47" },
    { value: "OM", label: "Oman", phone: "968" },
    { value: "PK", label: "Pakistan", phone: "92" },
    { value: "PW", label: "Palau", phone: "680" },
    { value: "PS", label: "Palestine State", phone: "970" },
    { value: "PA", label: "Panama", phone: "507" },
    { value: "PG", label: "Papua New Guinea", phone: "675" },
    { value: "PY", label: "Paraguay", phone: "595" },
    { value: "PE", label: "Peru", phone: "51" },
    { value: "PH", label: "Philippines", phone: "63" },
    { value: "PL", label: "Poland", phone: "48" },
    { value: "PT", label: "Portugal", phone: "351" },
    { value: "QA", label: "Qatar", phone: "974" },
    { value: "RO", label: "Romania", phone: "40" },
    { value: "RU", label: "Russia", phone: "7" },
    { value: "RW", label: "Rwanda", phone: "250" },
    { value: "KN", label: "Saint Kitts and Nevis", phone: "1-869" },
    { value: "LC", label: "Saint Lucia", phone: "1-758" },
    { value: "VC", label: "Saint Vincent and the Grenadines", phone: "1-784" },
    { value: "WS", label: "Samoa", phone: "685" },
    { value: "SM", label: "San Marino", phone: "378" },
    { value: "ST", label: "Sao Tome and Principe", phone: "239" },
    { value: "SA", label: "Saudi Arabia", phone: "966" },
    { value: "SN", label: "Senegal", phone: "221" },
    { value: "RS", label: "Serbia", phone: "381" },
    { value: "SC", label: "Seychelles", phone: "248" },
    { value: "SL", label: "Sierra Leone", phone: "232" },
    { value: "SG", label: "Singapore", phone: "65" },
    { value: "SK", label: "Slovakia", phone: "421" },
    { value: "SI", label: "Slovenia", phone: "386" },
    { value: "SB", label: "Solomon Islands", phone: "677" },
    { value: "SO", label: "Somalia", phone: "252" },
    { value: "ZA", label: "South Africa", phone: "27" },
    { value: "KR", label: "South Korea", phone: "82" },
    { value: "SS", label: "South Sudan", phone: "211" },
    { value: "ES", label: "Spain", phone: "34" },
    { value: "LK", label: "Sri Lanka", phone: "94" },
    { value: "SD", label: "Sudan", phone: "249" },
    { value: "SR", label: "Suriname", phone: "597" },
    { value: "SE", label: "Sweden", phone: "46" },
    { value: "CH", label: "Switzerland", phone: "41" },
    { value: "SY", label: "Syria", phone: "963" },
    { value: "TW", label: "Taiwan", phone: "886" },
    { value: "TJ", label: "Tajikistan", phone: "992" },
    { value: "TZ", label: "Tanzania", phone: "255" },
    { value: "TH", label: "Thailand", phone: "66" },
    { value: "TL", label: "Timor-Leste", phone: "670" },
    { value: "TG", label: "Togo", phone: "228" },
    { value: "TO", label: "Tonga", phone: "676" },
    { value: "TT", label: "Trinidad and Tobago", phone: "1-868" },
    { value: "TN", label: "Tunisia", phone: "216" },
    { value: "TR", label: "Turkey", phone: "90" },
    { value: "TM", label: "Turkmenistan", phone: "993" },
    { value: "TV", label: "Tuvalu", phone: "688" },
    { value: "UG", label: "Uganda", phone: "256" },
    { value: "UA", label: "Ukraine", phone: "380" },
    { value: "AE", label: "United Arab Emirates", phone: "971" },
    { value: "GB", label: "United Kingdom", phone: "44" },
    { value: "US", label: "United States", phone: "1" },
    { value: "UY", label: "Uruguay", phone: "598" },
    { value: "UZ", label: "Uzbekistan", phone: "998" },
    { value: "VU", label: "Vanuatu", phone: "678" },
    { value: "VE", label: "Venezuela", phone: "58" },
    { value: "VN", label: "Vietnam", phone: "84" },
    { value: "YE", label: "Yemen", phone: "967" },
    { value: "ZM", label: "Zambia", phone: "260" },
    { value: "ZW", label: "Zimbabwe", phone: "263" }
];
